git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
matrix:
  fast_finish: true
language: node_js
node_js:
- '7'
dist: trusty
addons:
  chrome: stable
notifications:
  slack: binary-group:xEVrYY0QGz7fbwJqi4LMWbBS
  email:
  - arnab@binary.com
  - apoorv@binary.com
branches:
  only:
  - master
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- yarn
install:
- yarn test
